### ISSUE TITLE
Feedback Skilopay

### ISSUE THREAD

**Issue by jonataa** [luismarquezzini/GraphBanking#1]
Olá, Luis,

Primeiro, parabéns pela realização do desafio e obrigado pela disponibilidade. Espero que esse feedback te agregue de alguma maneira e ajude a melhorar o seu projeto. O que vou colocar são apenas observações e sugestões de melhoria baseadas na minha experiência, então fique a vontade para discordar ou tirar dúvidas de algo que não faça sentido para você.

- Senti falta de uma explicação prévia no README a respeito de um banco PostgreSQL, talvez um item "Requisitos obrigatórios" dizendo em qual porta precisa rodar o banco, qual usuário e senha, etc. Por mais comum que o uso do Postgres seja em projetos Phoenix, isso poupa um tempo legal de quem pretende dar continuidade ou ajudá-lo no projeto, independente se é júnior ou não. O uso do docker nesse tipo de situação seria o ideal, mas uma simples explicação no readme já ajudaria bastante;
- Também senti falta da URL completa para consultas GraphQL no readme, tive que abrir o código para descobrir que é `/api`, facilitaria se tivesse no readme;
- Faltou tratar as mensagens de erros conforme [especificação GraphQL](https://github.com/graphql/graphql-spec/blob/master/spec/Section%207%20--%20Response.md#errors). Deveria ter feito como você mesmo fez no balanço negativo durante a abertura da conta, ou seja, o resolver precisa retornar algo assim: `{:error, "..."}`; 
- A schema da API não está conforme especificado no desafio (exemplo: `when` virou `insertedAt` e `uuid` virou `id`);
- Algumas sugestões para função `transfer_money`;
1. Poderia ter usado pattern matching para realizar as validações;
2. As consultas deveriam ter sido realizadas fora desse método, deixando apenas para validação das regras de negócio, como, por exemplo: saldo insuficiente, não permitir enviar para ele mesmo, etc. Além de evitar side effects, o método ficaria mais simples de testar. Eu faria algo mais ou menos assim:
```
# lib/graphbanking_web/resolvers/transaction.ex
...
  def transfer_money(
        _parent,
        %{sender: sender_uuid, address: address_uuid, amount: amount},
        _resolution
      ) do
    with sender when not is_nil(sender) <- Bank.get_account(sender_uuid),
         address when not is_nil(address) <- Bank.get_account(address_uuid) do
      Account.transfer_money(sender, address, amount)
    else
      nil -> {:error, "Account not found"}
    end
  end

# lib/graphbanking/account/account.ex
  def transfer_money(_attrs, _sender, _address, amount) when amount <= 0,
    do: {:error, "Can't transfer negative values"}

  def transfer_money(_attrs, %{amount: sender_amount}, _address, amount)
      when sender_amount < amount,
      do: {:error, "You don't have sufficient Money"}

  def transfer_money(_attrs, %{id: sender_id}, %{id: address_id}, amount)
      when sender_id === address_id,
      do: {:error, "you can't transfer money to yourself"}

  def transfer_money(attrs, sender, address, amount) do
     ...
  end
```
3. Experimente usar o https://hexdocs.pm/ecto/Ecto.Multi.html para múltiplas alterações, principalmente para evitar que aconteça um erro no meio da transação e os dados fiquem inconsistentes, por exemplo, numa transferência o dinheiro é retirado da conta origem, mas se por alguma razão o sistema não conseguir atualizar o saldo do destinatário (currentBalance - amount) esse valor estará perdido e a conta de origem ficará com valor a menos;
- Após uma transferência, o sistema não registrou a transação de entrada na conta destino, apenas a saída da origem. Imagine o extrato de uma conta que não possui movimentações, mas tem um saldo positivo, o dinheiro precisa vim de algum lugar. A mesma coisa com o saldo inicial na abertura, tinha que ter pelo menos o registro de entrada na conta;
- Achei bom que fez testes unitários, mas poderia ter focado mais nas funções de negócio ao invés do banco;
- Poderia realizar mais commits e explicar o "porquê" na descrição de cada um deles;
- Não entendi muito bem pq decidiu colocar as schemas do banco em pastas separadas (Transaction em lib/graphbanking/account e Account em lib/graphbanking/bank);
- E uma dica de ouro, sempre que armazene valores monetários como inteiro ou utilize a biblioteca [Decimal](https://hexdocs.pm/decimal/readme.html), tudo por causa do calculo de precisão:
```
iex(1)> 0.1 + 0.2
0.30000000000000004
```

Bom, acho que é isso, tentei analisar quase tudo, espero que algumas dessas observações façam sentido para você.

Qualquer dúvida por favor me avisa!

Abraços,

Jonata

**Comment by luismarquezzini** [comment]
Olá, Jonata.

Em primeiro lugar, muito obrigado pelo tempo dedicado ao feedback e pelos detalhes empregados nas observações.

Sobre a URL completa, eu creio que ela esteja no readme, salvo engano. Eu a inseri aqui pouco antes de especificar o que a API faz:
"Want to test? Please visit localhost:4000/api/graphiql from your browser. "

Fico feliz em apontar exatamente o que poderia ter melhorado no código, eu fiz com certa agilidade enquanto aprendia a linguagem, pois tive que me apressar um pouco lendo a documentação enquanto aprendia a linguagem. (Só aprendi Elixir e a usar graphql na semana que o teste me foi enviado, então foi tudo muito novo para mim). Mas gostei e muito especialmente de graphql. Elixir também, mas o jeito de pensar em elixir para mim é moderadamente novo, então vou ter que me esforçar para melhorar.

Sobre as pastas separadamente, na minha cabeça ficava mais organizado separar pelos módulos delas.

Abraços,

Luis
